openapi: 3.0.1
info:
  title: urlshortener
  version: 1.0.0
components:
  schemas:
    
    Click:
      type: object
      properties:
        ip:
          type: string
        time:
          type: string
          format: date

    FullUrlData:
      type: object
      properties:
        FullUrl:
          type: string

    ShortLink:
      type: object
      properties:
        FullUrl:
          type: string
        ShortId:
          type: string
        StatId:
          type: string
        ExpirationDate:
          type: string
          format: date
                 
    Stats:
      type: object
      properties:
        ClickCount: 
          type: integer
          format: int64
        ExpirationDate:
          type: string
          format: date
        Clicks:
          type: array
          items:
            $ref: '#/components/schemas/Click'
        
paths:
  /generate:
    post:
      operationId: generateShortLink
      requestBody:
        required: true
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/FullUrlData'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLink'
        405:
          description: "Invalid input"
          
  /stat/{statid}:
    get:
      summary: Get stats
      operationId: GetUrlStats
      parameters:
      - name: statid
        in: path
        description: defines stats of short url
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        400:
          description: Invalid ID supplied
          content: {}
          
  /{shorturl}:
    get:
      summary: redirect to full url
      operationId: Redirect
      parameters:
      - name: shorturl
        in: path
        description: short url
        required: true
        schema:
          type: string
      responses:
        301:
          description: redirect
        400:
          description: Invalid ID supplied
          content: {}